### ISSUE TITLE
No audio when viewing in Chrome on Android mobile

### ISSUE THREAD

**Issue by Russtopia** [BrOrlandi/StarWarsIntroCreator#24]
Android 7.1.2; ASUS_Z00TD Build/NHJ47F

Chromium SWE 58.0.3029.2839677

Awesome app! So much fun, thank you.

**Comment by BrOrlandi** [comment]
Yes, this is a know issue. Thanks for reporting it. I tried to fix it but without success. I will put hacktoberfest label and see if anyone could solve this.

Thank you!

**Comment by Haroenv** [comment]
Audio won’t play in Safari or Chrome because `.play()` is being called without user gesture. You’d need a button to start it

**Comment by BrOrlandi** [comment]
@Haroenv, I tried to put a button before, identifying the user device, but today it's not working anymore, I will try to work on that soon. Thanks for contributing!

**Comment by Graystripe17** [comment]
I'm having a similar issue on Mac OS Chrome. Similar to what Haroenv says, it only happens when the tab isn't active when the mp4 resource isn't being loaded, so like opening in a new tab. But if you click directly on it and wait for it to load, the sound works. I think it's because Chrome wants to stop autoplaying audio, kinda like when Youtube is opened in another tab.

Maybe fix by checking is browser active before loading the resource? Does anyone think that could work?

**Comment by Graystripe17** [comment]
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by BrOrlandi** [comment]
Hi @Graystripe17 !
Thanks for reporting it, I knew it should affect our website. We are working on a new version of the website, and we will try to fix it as soon as possible, and get it fixed for everyone. Thank you!

**Comment by BrOrlandi** [comment]
I have fixed in the new version of the website, we will be deploying it soon.

**Comment by BrOrlandi** [comment]
The new website version is live: http://starwarsintrocreator.kassellabs.io
@Graystripe17 @Russtopia @Haroenv please check it out.

Thanks!

**Comment by Russtopia** [comment]
Newest version as of May 22 2018 is working for me on desktop (win7 x64 Vivaldi (Chromium-based)) and Android mobile Chromium. Thanks!

**Comment by BrOrlandi** [comment]
Solved in the new website version.
